baseURL = 'https://matyasjankudlacek.cz/'
locale = 'en-us'
title = 'Matyáš Jan Kudláček'
theme = 'mjkud'

[markup]
  [markup.goldmark]
    duplicateResourceFiles = false
    [markup.goldmark.extensions]
      definitionList = true
      linkify = true
      linkifyProtocol = 'https'
      strikethrough = true
      table = true
      taskList = true
      [markup.goldmark.extensions.cjk]
        eastAsianLineBreaks = false
        eastAsianLineBreaksStyle = 'simple'
        enable = false
        escapedSpace = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = false
        [markup.goldmark.extensions.extras.insert]
          enable = false
        [markup.goldmark.extensions.extras.mark]
          enable = false
        [markup.goldmark.extensions.extras.subscript]
          enable = true
        [markup.goldmark.extensions.extras.superscript]
          enable = true
      [markup.goldmark.extensions.passthrough]
        enable = false
        [markup.goldmark.extensions.passthrough.delimiters]
          block = []
          inline = []
      [markup.goldmark.extensions.typographer]
        apostrophe = '&rsquo;'
        disable = false
        ellipsis = '&hellip;'
        emDash = '&mdash;'
        enDash = '&ndash;'
        leftAngleQuote = '&laquo;'
        leftDoubleQuote = '&ldquo;'
        leftSingleQuote = '&lsquo;'
        rightAngleQuote = '&raquo;'
        rightDoubleQuote = '&rdquo;'
        rightSingleQuote = '&rsquo;'
    [markup.goldmark.parser]
      autoDefinitionTermID = false
      autoHeadingID = true
      autoIDType = 'github'
      wrapStandAloneImageWithinParagraph = true
      [markup.goldmark.parser.attribute]
        block = false
        title = true
    [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = 'auto'
      [markup.goldmark.renderHooks.link]
        useEmbedded = 'auto'
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
  identifier = "about"
  name = "About"
  title = "About"
  url = "/about"
  weight = 10

  [[menu.main]]
  identifier = "cv"
  name = "CV"
  title = "CV"
  url = "/cv"
  weight = 20

  [[menu.main]]
  identifier = "friends"
  name = "Friends"
  title = "Become a Friend"
  url = "/friends"
  weight = 30

  [[menu.main]]
  identifier = "posts"
  name = "Posts"
  title = "Posts"
  url = "/posts"
  weight = 40

  [[menu.main]]
  identifier = "links"
  name = "Links"
  title = "Links"
  url = "/links"
  weight = 50

  [[menu.main]]
  identifier = "contact"
  name = "Contact"
  title = "Contact"
  url = "/contact"
  weight = 60
